name: benchmarks

on:
  workflow_run:
    workflows: [tests]
    branches: [master]
    types: [completed]

jobs:

  benchmark:
    name: Run the benchmark
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Create docker network
        run: docker network create data

      - name: Benchmark AIOHTTP
        uses: ./.github/actions/benchmark
        with:
          name: aiohttp
          network: data

      - name: Benchmark Blacksheep
        uses: ./.github/actions/benchmark
        with:
          name: blacksheep
          network: data

      - name: Benchmark Muffin
        uses: ./.github/actions/benchmark
        with:
          name: muffin
          network: data

      - name: Benchmark Quart
        uses: ./.github/actions/benchmark
        with:
          name: quart
          network: data

      - name: Benchmark Sanic
        uses: ./.github/actions/benchmark
        with:
          name: sanic
          network: data

      - name: Benchmark Starlette
        uses: ./.github/actions/benchmark
        with:
          name: starlette
          network: data

      - name: Benchmark Django
        uses: ./.github/actions/benchmark
        with:
          name: django
          network: data

      - name: Benchmark Falcon
        uses: ./.github/actions/benchmark
        with:
          name: falcon
          network: data

      - name: Benchmark FastApi
        uses: ./.github/actions/benchmark
        with:
          name: fastapi
          network: data

      - name: Results
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: ./results

  readme:
    name: Update Results
    needs: benchmark
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
      - uses: actions/setup-python@v2
      - run: python -m pip install -r render/requirements.txt
      - run: python render/render.py
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Commit changes
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -am "Update results"
          git tag ${{ steps.date.outputs.date }}
          git push -f --tags
          git push
